version: 2
buildCommand: npm run build
startCommand: bash start.sh
healthCheckPath: /api/health
envVars:
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    generateValue: true
  - key: DATABASE_URL
    fromDatabase:
      name: fathi-vlogs-db
      property: connectionString
